services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: game
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      R2DBC_URL: r2dbc:postgresql://db:5432/game
      JDBC_URL: jdbc:postgresql://db:5432/game
      DB_USER: game
      DB_PASSWORD: secret
      JWT_SECRET: very-secret-change-me
    ports:
      - "8080:8080"

volumes:
  db_data:
