spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://db:5432/game}
    username: ${DB_USER:game}
    password: ${DB_PASSWORD:secret}

  datasource:
    url: ${JDBC_URL:jdbc:postgresql://db:5432/game}
    username: ${DB_USER:game}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:14747a4a-e0b7-401a-9f11-d73b733b4fa5}
  expiration-ms: ${JWT_EXP_MS:86400000}
